### ISSUE TITLE
Continuous deployment to hosted site

### ISSUE THREAD

**Issue by BrandonClapp** [graydigital/home#66]
- fixed by #67 

It would be nice to have a WIP version of the site that is deployed on every merge. We might be a ways off from this.

- Consume Storybook package from `home` application.
- Dependabot hook that submits a new PR when new Storybook package has been pushed to upgrade the package(s) in the `home` app.
- Deploy static site when PR is merged to `home/main` (i.e. Netlify)

**Comment by ariperez** [comment]
agreed!  I'll work on this.

**Comment by ariperez** [comment]
#67
